# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '19.FIndCVS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 19.FIndCVS
	pod 'RxSwift', '6.5.0'
	pod 'RxCocoa', '6.5.0'
	pod 'SnapKit', '~> 5.6.0'
end
